---
title: "3. Plotting"
---

```{r}
#| label: setup
#| warning: false

# load libs
library(tidyverse)
library(here)

# source custom code
source(here('scripts/setup.R'))

# define global variables
custom_dpi = 600
custom_unit = 'cm'
custom_width = 18.2
custom_height = custom_width * 0.61803

```

## Read Data / Models

```{r}
#| label: read_info

df <- read_csv(
  here('data/processed/example.csv'),
  show_col_types = FALSE
)

mod_lm <- readRDS(here('mods/example.rds'))
```

## Create Plots

```{r}
#| label: fig-prediction
#| fig-cap: Relation of hp with mpg.

# create plot
plot_mod <-
  ggplot(
    df,
    aes(
      x = hp,
      y = mpg,
      color = as.factor(gear)
    )
  ) +
  geom_point() +
  geom_abline(
    slope = mod_lm$coefficients['hp'],
    intercept = mod_lm$coefficients['(Intercept)']
  ) +
  labs(
    title = 'Predicted Relation of hp and mpg',
    color = 'Gear'
  )


# show plot
plot_mod
```

## Save Plots


```{r}
#| label: save_plot
#| eval: false

ggsave(
  here('plots/example.png'),
  plot = plot_mod,
  width = custom_width,
  height = custom_height,
  units = custom_unit,
  dpi = custom_dpi
)
```